---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 2
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: IngressRoute
      name: overseerr
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`ask.lab.amolicob.cloud`)
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: lab.amolicob.cloud
  - target:
      kind: Certificate
    patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: ask.lab.amolicob.cloud
