---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-bedrock

resources:
  - configmap.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - statefulset.yaml
